### ISSUE TITLE
Use dust.config.whitespace = true

### ISSUE THREAD

**Issue by sethkinast** [smfoote/dust-demo#6]
Easier to understand example output, I think. Discuss?

(Requires you to update the version of Dust you're using, but cdnJS has the latest version)

**Comment by smfoote** [comment]
We've gone back and forth on this a few times already, but @tonya and I found that preserving whitespace makes the output _much_ harder to understand when the template is anything more than a couple of lines.

**Comment by tonya** [comment]
Is this a different option though? We used dust.optimizers.format to turn it on, and that indeed looked ugly, because it copied over the exact spacing from the template, which led to funny extraneous line breaks in the output.

**Comment by smfoote** [comment]
Yeah, it's the same. The thing we were doing was a hack. This is the new
way to do the same thing.

**Comment by smfoote** [comment]
Until we can come up with a better way of preserving whitespace, I'm going to close this issue.
